'use strict';
const $=id=>document.getElementById(id),fmt=v=>v.toLocaleString('de-DE',{maximumFractionDigits:5}),bin=(d,n)=>d.toString(2).padStart(n,'0');
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('main>section').forEach(s=>s.hidden=s.id!==b.dataset.panel);document.querySelectorAll('nav button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));stopAuto();}));
$('projector').onclick=()=>{const on=document.body.classList.toggle('projector');$('projector').setAttribute('aria-pressed',String(on));};
let secret=11,lo=0,hi=15,asks=0,answers='';
function drawSearch(){const finished=lo===hi;const pivot=Math.ceil((lo+hi)/2);$('numbers').innerHTML=Array.from({length:16},(_,i)=>`<span class="${i<lo||i>hi?'out':''}">${i}</span>`).join('');$('search-range').textContent=`Möglicher Bereich: ${lo} bis ${hi} · ${asks} Fragen`; $('ask').disabled=finished;$('ask').textContent=finished?'Zahl gefunden':`Ist die Zahl mindestens ${pivot}?`; $('search-code').textContent=finished?`Zahl ${secret} · Entscheidungen ${answers} · Binärcode ${bin(secret,4)}`:'';}
$('ask').onclick=()=>{const pivot=Math.ceil((lo+hi)/2),yes=secret>=pivot;asks++;answers+=yes?'1':'0';if(yes)lo=pivot;else hi=pivot-1;$('search-message').textContent=`${yes?'Ja':'Nein'}. ${yes?'Die Zahl ist mindestens':'Die Zahl ist kleiner als'} ${pivot}.`;drawSearch();};
function newSearch(number){secret=number;lo=0;hi=15;asks=0;answers='';$('search-message').textContent='Mit jeder Antwort verkleinert sich der mögliche Bereich.';drawSearch();}
$('search-reset').onclick=()=>newSearch(Math.floor(Math.random()*16));$('fixed-eleven').onclick=()=>newSearch(11);drawSearch();
let data,progress=0,timer=null;
function stopAuto(){if(timer!==null){clearInterval(timer);timer=null;}$('pause').disabled=true;if(data&&progress<data.bits)$('auto').disabled=false;}
function resetADC(){stopAuto();const n=Number($('bits').value),r=Number($('reference').value),v=Number($('input').value);$('input').max=r;const valid=$('input').value.trim()!==''&&Number.isFinite(v)&&v>=0&&v<=r;$('input-error').hidden=valid;$('input-error').textContent=`Geben Sie eine Spannung von 0 bis ${r} V ein.`;if(!valid){data=null;['keep','discard','auto'].forEach(x=>$(x).disabled=true);$('result').textContent='Keine gültige Eingangsspannung.';$('held').textContent='—';$('trial-voltage').textContent='—';$('voltage-chart').innerHTML='';$('bit-row').innerHTML='';$('trace').innerHTML='';$('prompt').textContent='Eingangsspannung prüfen.';return;}data=SAR.convert(v,n,r);progress=0;$('feedback').textContent='Vergleichen Sie zunächst die beiden Spannungen.';drawADC();}
function voltageChart(input,trial,low,high,ref){const x=v=>50+v/ref*600;return `<svg viewBox="0 0 710 205" role="img" aria-label="Eingang ${fmt(input)} Volt, Vergleich ${fmt(trial)} Volt, möglicher Bereich ${fmt(low)} bis ${fmt(high)} Volt"><rect x="${x(low)}" y="45" width="${Math.max(1,x(high)-x(low))}" height="78" fill="#e0eef9"/><line x1="50" x2="650" y1="125" y2="125" stroke="#6a8295" stroke-width="2"/><text x="50" y="160">0 V</text><text x="650" y="160" text-anchor="end">${fmt(ref)} V</text><line x1="${x(input)}" x2="${x(input)}" y1="25" y2="125" stroke="#004b80" stroke-width="4"/><circle cx="${x(input)}" cy="30" r="6" fill="#004b80"/><line x1="${x(trial)}" x2="${x(trial)}" y1="65" y2="125" stroke="#b65b00" stroke-width="4" stroke-dasharray="6 4"/><text x="50" y="20">Blau: Uₑ = ${fmt(input)} V</text><text x="50" y="185">Orange: U<tspan baseline-shift="sub">DAC</tspan> = ${fmt(trial)} V · Hellblau: möglicher Bereich</text></svg>`;}
function drawADC(){const done=progress===data.bits,current=data.trace[Math.min(progress,data.bits-1)],previous=progress?data.trace[progress-1]:null,code=previous?previous.code:0;const lower=previous?previous.low:0,upper=previous?previous.high:data.ref;
 $('held').textContent=fmt(data.input)+' V';$('trial-voltage').textContent=fmt(done?data.low:current.voltage)+' V';$('step-size').textContent=fmt(data.step)+' V';$('voltage-chart').innerHTML=voltageChart(data.input,done?data.low:current.voltage,lower,upper,data.ref);
 $('bit-row').innerHTML=Array.from({length:data.bits},(_,i)=>{const b=data.bits-1-i,decided=i<progress,active=!done&&i===progress,val=decided?((code>>b)&1):active?'1':'?';return `<div class="bit ${decided?'done':active?'active':''}"><small>2<sup>${b}</sup> = ${2**b}</small><b>${val}</b></div>`;}).join('');
 $('prompt').textContent=done?`Alle ${data.bits} Bits entschieden.`:`Schritt ${progress+1} von ${data.bits}: Prüfcode ${bin(current.trial,data.bits)}. Ist ${fmt(data.input)} V mindestens ${fmt(current.voltage)} V?`;
 $('trace').innerHTML=data.trace.slice(0,progress).map((t,i)=>`<tr><td>${i+1}</td><td>${bin(t.trial,data.bits)}</td><td>${fmt(t.voltage)} V</td><td>${t.keep?'Behalten':'Zurücksetzen'}</td><td>${bin(t.code,data.bits)}</td></tr>`).join('');
 ['keep','discard','auto'].forEach(id=>$(id).disabled=done||timer!==null);$('pause').disabled=timer===null;
 $('result').textContent=done?`Digitalwert: D = ${data.code} · Binärcode ${data.binary} · Intervall: ${fmt(data.low)} V bis ${data.code===data.count-1?'einschließlich':'unter'} ${fmt(data.high)} V · Intervallmitte Uq = ${fmt(data.mid)} V.`:'Das Ergebnis erscheint nach allen Bitentscheidungen.';
}
function choose(keep){if(!data||progress>=data.bits)return;const t=data.trace[progress];if(keep!==t.keep){$('feedback').textContent=`Noch einmal vergleichen: ${fmt(data.input)} V ist ${t.keep?'mindestens':'kleiner als'} ${fmt(t.voltage)} V. Das Bit muss ${t.keep?'behalten':'zurückgesetzt'} werden.`;return;}$('feedback').textContent=`Richtig: Bit ${t.bit} wird ${keep?'behalten':'zurückgesetzt'}.`;progress++;if(progress===data.bits)stopAuto();drawADC();}
$('keep').onclick=()=>choose(true);$('discard').onclick=()=>choose(false);$('auto').onclick=()=>{if(!data||progress>=data.bits)return;timer=setInterval(()=>choose(data.trace[progress].keep),1200);drawADC();};$('pause').onclick=()=>{stopAuto();drawADC();};['bits','reference'].forEach(id=>$(id).addEventListener('change',resetADC));$('input').addEventListener('input',resetADC);$('adc-reset').onclick=resetADC;$('example').onclick=()=>{$('bits').value='4';$('reference').value='4';$('input').value='2.8';resetADC();};resetADC();
function drawSensor(){const n=Number($('sensor-bits').value),count=2**n,d=Number($('sensor-code').value);$('sensor-code').max=count-1;const valid=$('sensor-code').value.trim()!==''&&Number.isInteger(d)&&d>=0&&d<count;$('sensor-error').hidden=valid;$('sensor-error').textContent=`Digitalwert muss ganzzahlig zwischen 0 und ${count-1} liegen.`;if(!valid){$('sensor-path').innerHTML='';$('sensor-calculation').textContent='';$('sensor-interval').textContent='Digitalwert prüfen.';$('sensor-chart').innerHTML='';return;}const step=4/count,mid=(d+.5)*step,temp=mid/4*100;$('sensor-path').innerHTML=`<div>Digitalwert<strong>${d} · ${bin(d,n)}</strong></div><div>Intervallmitte<strong>${fmt(mid)} V</strong></div><div>Temperaturschätzung<strong>${fmt(temp)} °C</strong></div>`;$('sensor-calculation').textContent=`ΔU = 4 V / ${count} = ${fmt(step)} V. Uq = (${d} + 0,5) · ${fmt(step)} V = ${fmt(mid)} V. Temperatur = Uq / 4 V · 100 °C = ${fmt(temp)} °C.`;$('sensor-interval').textContent=`Der Code steht für ${fmt(d*step)} V bis ${d===count-1?'einschließlich':'unter'} ${fmt((d+1)*step)} V. Temperaturbereich: ${fmt(d/count*100)} °C bis ${d===count-1?'einschließlich':'unter'} ${fmt((d+1)/count*100)} °C. Schrittweite: ${fmt(100/count)} °C.`;$('sensor-chart').innerHTML=`<svg viewBox="0 0 710 260" role="img" aria-label="Lineare Sensorkennlinie mit markiertem Schätzwert"><path d="M60 20V210H650" fill="none" stroke="#6a8295" stroke-width="2"/><path d="M60 210L620 35" fill="none" stroke="#004b80" stroke-width="3"/><circle cx="${60+temp/100*560}" cy="${210-mid/4*175}" r="7" fill="#b65b00"/><text x="60" y="245">0 °C</text><text x="570" y="245">100 °C</text><text x="8" y="35">4 V</text><text x="8" y="210">0 V</text><text x="130" y="30">Uₑ = 0,04 V/°C · Temperatur</text></svg>`;}
$('sensor-bits').onchange=drawSensor;$('sensor-code').oninput=drawSensor;drawSensor();
const quiz=[{q:'Welche Aufgabe hat der DAC innerhalb des ADC?',a:['Er erzeugt aus dem Prüfcode eine Vergleichsspannung.','Er hält die Eingangsspannung fest.','Er verhindert Aliasing.'],correct:0,why:'Der DAC wandelt den digitalen Prüfcode in eine analoge Vergleichsspannung um.'},{q:'Was geschieht bei Uₑ = U_DAC in unserem Modell?',a:['Das Bit wird zurückgesetzt.','Das Bit bleibt gesetzt.','Die Wandlung wird abgebrochen.'],correct:1,why:'Die untere Intervallgrenze gehört zum neuen Intervall: Gleichheit bedeutet behalten.'},{q:'Wie viele Vergleiche braucht unser 8-Bit-SAR-ADC pro Wandlung?',a:['256','4','8'],correct:2,why:'Jeder Vergleich entscheidet ein Bit. Bei 8 Bit werden acht Vergleiche benötigt.'},{q:'Warum bleibt die Quantisierung trotz der Bitentscheidungen bestehen?',a:['Der Komparator misst die Spannung exakt.','Ein Code steht weiterhin für ein ganzes Spannungsintervall.','Der ADC liefert immer die genaue Eingangsspannung.'],correct:1,why:'Der Digitalwert bestimmt ein Intervall, nicht die genaue Spannung darin.'}];
$('quiz').innerHTML=quiz.map((q,i)=>`<fieldset><legend>${i+1}. ${q.q}</legend>${q.a.map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}">${a}</label>`).join('')}<p id="qfeedback${i}" aria-live="polite"></p></fieldset>`).join('');$('check-quiz').onclick=()=>{let score=0;quiz.forEach((q,i)=>{const selected=document.querySelector(`input[name="q${i}"]:checked`),right=selected&&Number(selected.value)===q.correct;if(right)score++;$('qfeedback'+i).textContent=!selected?'Bitte wählen Sie eine Antwort.':`${right?'Richtig.':'Noch nicht richtig.'} ${q.why}`;});$('quiz-feedback').textContent=`${score} von ${quiz.length} Antworten richtig.`;};

